### ISSUE TITLE
Please disable the <CR> mapping when the completion menu is visible (pumvisible)

### ISSUE THREAD

**Issue by char101** [tmsvg/pear-tree#1]
Otherwise when I select an entry in the completion menu it will results in a newline.

Thanks.

**Comment by tmsvg** [comment]
Hi there! I'm not experiencing the behavior you describe. In my testing, pressing \<CR\> simply accepts the completion entry without inserting a newline. Are you using an autocompletion plugin, or do you have mappings in your config that affect the completion menu?

Regardless, to disable pair expansion when the completion menu is visible, you can put the following in your vimrc:

```vim
imap <expr> <CR> !pumvisible() ? "\<Plug>(PearTreeExpand)" : "\<CR>"
```

**Comment by char101** [comment]
Hi,

Thanks for your reply. I do have this mapping in my vimrc

```viml
inoremap <expr> <CR>       pumvisible() ? "\<C-y>" : "\<CR>"
```

Adding the mapping above seems to do the trick.
