### ISSUE TITLE
doesn't work with non-english keymaps

### ISSUE THREAD

**Issue by habamax** [tmsvg/pear-tree#11]
If you activate

	set keymap=russian-jcukenmac

and try to write a word `хорошо` you end up with the `[орошо`

`хъХЪэЭ` letters are affected, instead of russian letter I get:
```
х [
Х {
ъ ]
Ъ }
э '
Э "
```

**Comment by tmsvg** [comment]
Thanks for reporting this. Let me know if you still have problems.

**Comment by habamax** [comment]
Thank you!
