### ISSUE TITLE
Bug reporting

### ISSUE THREAD

**Issue by kkoomen** [tmsvg/pear-tree#16]
I want to mention that this is the first module that does auto-pairing right. I've been using and searching for a good auto-pairing plugin for ~5 years and I discovered this one last week. Before this module I used [auto-pairs](https://github.com/jiangmiao/auto-pairs) which is the most popular one, looking at the amount of starts, but I do think this module is definitely underrated. The logic of closing is exactly what I have been looking for and finally somebody did it right! Thanks again for this module and I really want to contribute to the module! Is there a global list of TODOs that has to be done or do you also have plannings for the feature? Maybe I could help out n_n

<hr />

**Something different:** I did found a scenario that might not have been noticed by people yet, but when I have this scenario in HTML (where `|` indicates the cursor):

```
<div class="|>
```

I do expect the result to be:
```
<div class="|">
```

Do you think this is fixable at core level? I really hope so. I know this doesn't work right now as expected because pear-tree doesn't insert when typing something when there are characters on the right of cursor.

**Comment by tmsvg** [comment]
Hello! Sorry for the slow response. The HTML issue is resolved in version 0.8. As for your first question, I don't really keep a list of things to do. I consider the plugin to be pretty close to feature complete, so most of the work that needs to be done comes from bug reports and feature requests. Thanks for your interest.
