### ISSUE TITLE
Add backtick support for JS template literals

### ISSUE THREAD

**Issue by apazzolini** [tmsvg/pear-tree#17]
Javascript has the concept of template literals that let you run functions on backtick strings before the argument and literals are joined. This is a popular pattern, especially with libraries like [Styled Components](https://www.styled-components.com/).

pear-tree fails to detect the initial backtick as opening the string (presumably because it's attached to the word to the left). For example:

```
const Row = styled.div`
  display: flex;
`
```

In this case, the initial backtick attached to the `div` wouldn't generate the matching pair. Also, when manually typing the closing backtick, pear-tree detects it as the start of an expression and generates a second backtick on the third line.

Would it be possible to support this functionality?

Thanks!

**Comment by aeosynth** [comment]
template literal functions are called [tagged templates](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates)

**Comment by tmsvg** [comment]
Hello! Sorry for the slow response. I've added a new option `not_at` that allows you to give a list of regex patterns and prevent pairing at text that matches one of the patterns. The default value for the backtick is `['\w']` which means it will not be paired when typed after a word (more info in `:h pear-tree-rule-options`). You now just need to change the default value to get the behavior you want:

```vim
" $VIMFILES/after/ftplugin/javascript.vim

" Close backticks anywhere:
let b:pear_tree_pairs = {'`': {'closer': '`', 'not_at': []}, ...}

" Or don't close backticks on an empty line:
let b:pear_tree_pairs = {'`': {'closer': '`', 'not_at': ['^\s*']}, ...}
```

Hope this works for you.

**Comment by apazzolini** [comment]
Hey, thanks for adding this! Everything seems to be working as expected now. 👍
