### ISSUE TITLE
Error when smart enabled and using /** */

### ISSUE THREAD

**Issue by sandangel** [tmsvg/pear-tree#2]
I got an error when writing JSdoc for javascript.jsx filetype.
so when I type the second `*` in `/**`, this error happened.

```sh
Error detected while processing function pear_tree#insert_mode#TerminateOpener[36]..pear_tree#GetRule:
line    2:
E712: Argument of get() must be a List or Dictionary
```

**Comment by tmsvg** [comment]
Thank you for raising this issue. The latest commit fixes it. Please update Pear Tree and let me know if it fixes it for you.
