### ISSUE TITLE
Insert spaces before closing characters

### ISSUE THREAD

**Issue by evanrelf** [tmsvg/pear-tree#22]
It would be really cool if pear-tree inserted spaces like auto-pairs does.

Example from [jiangmiao/auto-pairs](https://github.com/jiangmiao/auto-pairs):

> Insert spaces before closing characters, only for [], (), {}
> ```
> input: {|} (press <SPACE> at |)
> output: { | }
>
> input: {|} (press <SPACE>foo} at |)
> output: { foo }|
>
> input: '|' (press <SPACE> at |)
> output: ' |'
> ```

**Comment by tmsvg** [comment]
I can see this being useful. I will add it soon.

**Comment by Tummetott** [comment]
I'd love this feature as well. Very usefull for bash scripting

**Comment by Tummetott** [comment]
I put the following in my vimrc:
`imap <Space> <Plug>(PearTreeSpace)`

```
input: {|} (press <SPACE> at |)
output: { | }

input: { (|) } (press <SPACE> at |)
output: { ( |) }
expected: output: { ( | ) }

```
