### ISSUE TITLE
Detect comments for smart openers and smart closers

### ISSUE THREAD

**Issue by bryclee** [tmsvg/pear-tree#26]
I've noticed that the smart openers and smart closers don't quite work when there is an unpaired paren or bracket within a comment. For example:

```javascript
// :( <- miscellaneous unpaired paren inside a comment

test(|)
```

I'd expect if I were to press `)`, that the cursor would then move to
```javascript
test()|
```

Is it possible to ignore comments when deciding whether to use the smart closers or not?

**Comment by tmsvg** [comment]
Use the `'not_in'` option in your pair rules:

```vim
let g:pear_tree_pairs = {
            \ '(': {'closer': ')', 'not_in': ['Comment']},
            \ '{': {'closer': '}', 'not_in': ['Comment']}
            " etc.
            \ }
```

**Comment by bryclee** [comment]
Hm... I tested this out with a minimal configuration but it still wasn't producing what I was hoping for.

In the above example, I was hoping to end up with the cursor like `test()|`, but instead I got `test()|)`

I'm using these settings:
```
Plug 'tmsvg/pear-tree'
let g:pear_tree_repeatable_expand = 0
let g:pear_tree_smart_openers = 1
let g:pear_tree_smart_closers = 1
let g:pear_tree_smart_backspace = 1
let g:pear_tree_pairs = {
            \ '(': {'closer': ')', 'not_in': ['Comment']},
            \ '{': {'closer': '}', 'not_in': ['Comment']},
            \ '[': {'closer': ']', 'not_in': ['Comment']}
            \ }
```

**Comment by tmsvg** [comment]
I should have mentioned, https://github.com/tmsvg/pear-tree/commit/4f3bc71e979a7ad743eb789aaaf8c23447cb44e7 fixed an issue that would have prevented this particular example from working. Try updating and see if it works.

**Comment by bryclee** [comment]
Thanks! After updating, this is working.
