### ISSUE TITLE
How to disable the <CR> mapping ?

### ISSUE THREAD

**Issue by frazrepo** [tmsvg/pear-tree#29]
Hi there,

Is there a way to disable the <CR> mapping which remove the closing character and restore it automatically when quitting insert mode.

I use jk as <ESC> and it doesn't work.

with \<CR> and \<ESC>

```
func main() {
    //Do something

}
```
with \<CR> and jk

```
fun main() {
    // quitting insert mode with jk doesnt' fill automatically the closing character
```

**Comment by tmsvg** [comment]
Hello! You can make `jk` reinsert the closing character by replacing  `inoremap jk <Esc>` with `imap jk <Plug>(PearTreeFinishExpansion)` in your vimrc.

If you still want disable the `<CR>` mapping, `let g:pear_tree_map_special_keys = 0` prevents Pear Tree from mapping `<CR>`, `<BS>`, and `<Esc>` so you can manually map only the ones you want.

See `:h pear-tree-mappings` and `:h g:pear_tree_map_special_keys`

**Comment by frazrepo** [comment]
Great ! Thank you, It works flawlessly
