### ISSUE TITLE
`not_at` doesn't always work with wildcard pattern

### ISSUE THREAD

**Issue by bryclee** [tmsvg/pear-tree#31]
I'm trying to configure pear-tree to use a `<*>` opener with `.tsx` files, so I need to support JSX tags as well as Typescript notation.

In particular, I need to support typescript generics, so something like below should not be expanded:
```
useHook<AppState>( ...someArgs)
```
And something like below should be expanded:
```
return <div></div>
```

Currently my setting looks like:
```
let g:pear_tree_pairs = {
      \ '<*>': { 'closer': '</*>',
      \          'not_if': ['br', 'hr', 'img', 'input', 'link', 'meta',
      \                  'area', 'base', 'col', 'command', 'embed',
      \                  'keygen', 'param', 'source', 'track', 'wbr'],
      \          'not_like': '{[^}]*$\|/$',
      \          'until': '[^a-zA-Z0-9-._]',
      \          'not_at': ['[^> ]<[^>]*'],
      \          'not_in': ['String']
      \        }
      \ }
```

I'm using `'not_at': ['[^> ]<[^>]*']` to detect whether the tag fits in the right place - basically searching for whether the opener is preceded by a non-space or angle bracket. However, this doesn't work when typing something like `test<T>` because at `l:text_before_opener` is determined by length of opener. https://github.com/tmsvg/pear-tree/blob/ace7d4104a8c102d3d7c2c62c15c146982d7d846/autoload/pear_tree/insert_mode.vim#L97

Does it make sense to have this be determined by the full match?

**Comment by tmsvg** [comment]
Should be fixed now. Thanks
