### ISSUE TITLE
Jump to Matching Dollar Sign Pair

### ISSUE THREAD

**Issue by jasonkena** [tmsvg/pear-tree#37]
```
let b:pear_tree_pairs = {
            \ '(': {'closer': ')'},
            \ '[': {'closer': ']'},
            \ '{': {'closer': '}'},
            \ "``": {'closer': "''"},
            \ '$': {'closer': '$'}
            \ }

```
Pear-tree is able to successfully enter the matching pair, but `imap <C-l> <Plug>(PearTreeJump)` does not work with the dollar sign.

Background info: Used for LaTeX equations

**Comment by tmsvg** [comment]
Thanks for reporting. It should be fixed now.
