### ISSUE TITLE
Closing bracket seems to disappear after pressing enter

### ISSUE THREAD

**Issue by Nil-Cipher** [tmsvg/pear-tree#46]
Hello, I'm new to all this, but the auto-completed closing bracket disappears if I press enter while the cursor is in between the brackets. Is this supposed to happen, and how do I prevent it?

**Comment by 0xMH** [comment]
> Note that the closing pair disappears after pressing <CR>. This is required to not break dot-repeat, but it will be automatically restored later.

Quoting from the README here. 

you can prevent erasing the closing string by setting
`g:pear_tree_repeatable_expand` to `0`.

**Comment by tmsvg** [comment]
Thanks @0xMH, yes this is expected behavior. The closing bracket reappears after you leave insert-mode.

`let g:pear_tree_repeatable_expand = 0` prevents this (at the expense of losing dot-repeatability).
