### ISSUE TITLE
 Argument of count() must be a List or Dictionary

### ISSUE THREAD

**Issue by thrisp** [tmsvg/pear-tree#5]
Error detected while processing function pear_tree#insert_mode#TerminateOpener[10]..pear_tree#insert_mode#CloseSimpleOpener[1]..<SNR>129_ShouldCloseSimpleOpener:
line   23:
E712: Argument of count() must be a List or Dictionary

I just installed this to try it, this is the default behavior I'm getting trying to type any type of opener ( e.g.
{, [, etc) inside a quote. 

Seemingly I should be able to do this by default without error, and then configure as needed for higher orders in the future, what do I do here?

**Comment by tmsvg** [comment]
What version of Vim are you using? Are you using the newest Pear Tree commit?

**Comment by tmsvg** [comment]
This issue should have been fixed recently. Please update Pear Tree and let me know if you still have problems. Thanks!
