### ISSUE TITLE
Unwanted angular bracket completion

### ISSUE THREAD

**Issue by PranavReddyP16** [tmsvg/pear-tree#54]
I use a lot of C++ and I do not want bracket completion for angular brackets, namely '<' and '>'. Is there any way to disable this? I couldn't find any.
 Thanks in advance.

**Comment by adworacz** [comment]
Looking at the [defaults](https://github.com/tmsvg/pear-tree#defaults), pear-tree doesn't expand <> brackets.

So if you added your own config - remove it. Or it sounds like another plugin may be doing the expansion for you?

**Comment by tmsvg** [comment]
Hi,

+1 to the previous comment, this isn't default behavior. You need to find the source of the behavior and fix it, first by checking if it's defined in a Pear Tree map

```
echo g:pear_tree_pairs
echo b:pear_tree_pairs
```

(If so, find where that's being set and remove it)

Alternatively, there could be another plugin providing this behavior.
