### ISSUE TITLE
Is there a way to jump to the position which is just after the current match pairs?

### ISSUE THREAD

**Issue by rainbowrun** [tmsvg/pear-tree#55]
For example, in C++, we need a semicolon at the end of every line, so if I call the function Foo with parameter 24, by using this plugin, I will have:

Foo(24|)

Notice '|' is where the cursor is, and I want to move it after ')' so that I can add ';'.

**Comment by emerdenny** [comment]
I think <Plug>(PearTreeJump) is what you want (see bottom of readme), just have to map it to something

**Comment by tmsvg** [comment]
Yes, Plug(PearTreeJump) achieves this. It's unmapped by default, but you just need to map it in your vimrc. Ex:

```
imap <C-l> <Plug>(PearTreeJump)
```

Alternatively, in this particular example, entering `)` will also move you past it instead of inserting another `)`.

**Comment by rainbowrun** [comment]
Thanks for the tip! It worked for me.
