### ISSUE TITLE
Cursor not a the good position when trying to add cariage return.

### ISSUE THREAD

**Issue by 945fc41467** [tmsvg/pear-tree#59]
Hello,

I tried to set my tex.vim like this (with the `^M` in the second line, I also tried `\^M`) :

```vim
let b:pear_tree_pairs = extend(deepcopy(g:pear_tree_pairs), {
            \ '\\begin{*}': {'closer': '^M\\end{*}', 'until': '[{}[:space:]]'},
            \ '\\left(': {'closer': '\\right)'},
            \ '\\left[': {'closer': '\\right]'},
            \ '\\left|': {'closer': '\\right|'},
            \ '\\left\\{': {'closer': '\\right\\}'},
            \ '\\left.': {'closer': '\\right.'},
            \ '$$': {'closer': '$$'},
            \ '\\{': {'closer': '\\}'},
            \ '\\(': {'closer': '\\)'},
            \ '\\[': {'closer': '\\]'},
            \ '$': {'closer': '$'}
            \ }, 'keep')
```

The expected result is:

```latex
\begin{anything}|
\end{anything}
```

Instead I obtain:

```latex
\begin{anything}
|\end{anything}
```

Am I doing it the wrong way ? Is there a proper way to append a new line ? I don’t understand the behavior.
Thanks.

**Comment by tmsvg** [comment]
Hello!

Control characters like `^M` are not supported in pair definitions, and opening/closing pair strings need to span a single line.

I'm not too familiar with TEX, but my impression is that most use cases for `\begin` and `\end` would be like:
```
\begin{anything}
% Some more stuff
\end{anything}
```

(with `\begin` and `\end` on separate lines)

OR

```
\begin{anything} Some more stuff \end{anything}
```

(with `\begin` and `\end` on the same line)

Pear Tree's behavior has those use cases in mind. If you remove `^M` from the closing pair, simply hitting `<CR>` after `\begin` will move your cursor to the next line and push `\end` to the line below:

```
\begin{anything}|\end{anything}
```

after hitting `<CR>` becomes:

```
\begin{anything}
|
\end{anything}
```

I'm closing the issue as this exact use case is not supported, but I think the existing `<CR>` behavior works well enough if you remove `^M` from the closing pair.

**Comment by 945fc41467** [comment]
Thanks for your answer.

Actually, most of text commands take parameters:

```latex
\begin{minipage}[t]{\linegoal}
    content of the minipage
\end{minipage}
```

so, it would be more ergonomic to let the user go to the next line when he want.

As you said this use case is not supported, you can consider label it as a feature request.

**Comment by tmsvg** [comment]
I see. 

I could potentially come up with a better way of enabling this, but a workaround with the capabilities Pear Tree has now would be to use the following mapping:

```
imap } <Plug>(PearTreeOpener_})<Plug>(PearTreeExpand)<BS>
```

Explanation:
- `<Plug>(PearTreeOpener_})` triggers the auto-close for the `\begin{*}` when } is pressed
- `<Plug>(PearTreeExpand)` immediately expands the pair after it is inserted.
- <BS> moves back to the previous line

I've only played around with it a little bit, so there could be some quirks, but it appears to work alright.

Note: if `g:pear_tree_repeatable_expand = 1`, then the `\end` line will disappear until you exit insert mode
