### ISSUE TITLE
Pairing support in command line

### ISSUE THREAD

**Issue by segeljakt** [tmsvg/pear-tree#7]
Hi, first of all, this plugin is amazing.

I'm wondering whether it would be possible to extend it with support for pairing in command line mode. It might be useful when inputting strings or parentheses for function arguments.

**Comment by tmsvg** [comment]
Thanks! Pear Tree does work in the command-line window (`:h cmdwin`). This is better suited for writing more complex commands anyway, so the work needed to add support for command-line mode would not be practical.
